// <auto-generated />
using System;
using DocumentaleMarta.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocumentaleMarta.Data.Migrazioni
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261009221432_NoteCompletamento")]
    partial class NoteCompletamento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("DocumentaleMarta.Core.Modelli.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icona")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("Ordine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PercorsoRelativo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.HasIndex("PercorsoRelativo")
                        .IsUnique();

                    b.ToTable("Aree");
                });

            modelBuilder.Entity("DocumentaleMarta.Core.Modelli.Cartella", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Archiviata")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AreaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completato")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("DataCompletamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DataScadenza")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteCompletamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("PercorsoRelativo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ricorrenza")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("DataScadenza");

                    b.HasIndex("PercorsoRelativo")
                        .IsUnique();

                    b.ToTable("Cartelle");
                });

            modelBuilder.Entity("DocumentaleMarta.Core.Modelli.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartellaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCaricamento")
                        .HasColumnType("TEXT");

                    b.Property<long>("Dimensione")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estensione")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeFile")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("PercorsoRelativo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatoIndicizzazione")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CartellaId");

                    b.HasIndex("Hash");

                    b.HasIndex("PercorsoRelativo")
                        .IsUnique();

                    b.ToTable("Documenti");
                });

            modelBuilder.Entity("DocumentaleMarta.Core.Modelli.Cartella", b =>
                {
                    b.HasOne("DocumentaleMarta.Core.Modelli.Area", "Area")
                        .WithMany("Cartelle")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("DocumentaleMarta.Core.Modelli.Documento", b =>
                {
                    b.HasOne("DocumentaleMarta.Core.Modelli.Cartella", "Cartella")
                        .WithMany("Documenti")
                        .HasForeignKey("CartellaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cartella");
                });

            modelBuilder.Entity("DocumentaleMarta.Core.Modelli.Area", b =>
                {
                    b.Navigation("Cartelle");
                });

            modelBuilder.Entity("DocumentaleMarta.Core.Modelli.Cartella", b =>
                {
                    b.Navigation("Documenti");
                });
#pragma warning restore 612, 618
        }
    }
}
